#!/bin/bash
# https://dev.mysql.com/downloads/mysql/
set -o errexit

function _print_sep() {
    printf "%$(tput cols)s\n" | tr ' ' "$1"
}

# Define color codes
RED="\033[1;31m"
GREEN="\033[1;32m"
YELLOW="\033[1;33m"
BLUE="\033[1;36m"
GRAY="\033[1;90m"
NONE="\033[0m"

function _logger() {
    local FNAME=$(basename "${BASH_SOURCE[1]}")
    local SOURCE="${BLUE}[${FNAME}:${BASH_LINENO[0]}]${NONE}"
    local TIMESTAMP_PREFIX="${BLUE}$(date +'%Y-%m-%d %H:%M:%S')${NONE}"

    case "$1" in
        debug)
            echo -e "${TIMESTAMP_PREFIX} ${SOURCE} ${BLUE}[DEBUG] $2 ${NONE}"
            ;;
        info)
            echo -e "${TIMESTAMP_PREFIX} ${SOURCE} ${GREEN}[INFO] $2 ${NONE}"
            ;;
        warn)
            echo -e "${TIMESTAMP_PREFIX} ${SOURCE} ${YELLOW}[WARN] $2 ${NONE}"
            ;;
        error)
            echo -e "${TIMESTAMP_PREFIX} ${SOURCE} ${RED}[ERROR] $2 ${NONE}"
            ;;
        *) ;;
    esac
}

# Define golabal variables
IP_ADDR=$(ip -4 addr show | grep inet | grep -v 127.0.0.1 | awk 'NR==1 {print $2}' | cut -d'/' -f1)
MYSQL_HOME="${4:-/usr/local/mysql}"
MYSQL_LISTEN_PORT=${5:-3306}

function install() {
    local MYSQL_VER="$1"
    local MYSQL_V=$(echo ${MYSQL_VER} | cut -d'.' -f1,2)
    local MYSQL_PKG_PREFIX="mysql-${MYSQL_VER}-linux-glibc2.28-x86_64"
    local MYSQL_URL="https://cdn.mysql.com/Downloads/MySQL-${MYSQL_V}/${MYSQL_PKG_PREFIX}.tar.xz"
    local MYSQL_ROOT_PASSWD="${2:-AAAaaa12#$}"
    local readonly MYSQL_CONF="/etc/my.cnf"
    local REMOTE_LOGIN_CMD="mysql -h ${IP_ADDR} -P ${MYSQL_LISTEN_PORT} -u root -p${MYSQL_ROOT_PASSWD}"
    local INIT_SQL="ALTER USER 'root'@'localhost' IDENTIFIED BY '${MYSQL_ROOT_PASSWD}';
        RENAME USER 'root'@'localhost' TO 'root'@'%';
        GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
        FLUSH PRIVILEGES;"
    local SELECT_USER_SQL="SELECT Host, User, authentication_string FROM mysql.user;"

    # 1. Validation Parameters
    _logger info "1. Validation Parameters"
    local MYSQL_VERS=("8.0.41" "8.4.4" "9.2.0")
    [[ ! -z ${MYSQL_VER} ]] && echo ${MYSQL_VERS[@]} | grep -wq "${MYSQL_VER}" || { \
        _logger error "Version mismatch. Please choose from the below." && \
        echo -e "official recommended versions: ${MYSQL_VERS[@]}" && exit 1; }

    [[ ! -d ${MYSQL_HOME} ]] || { _logger error "MySQL is already installed in ${MYSQL_HOME}." && exit 1; }

    # 2. Download and extract
    _logger info "2. Downloading and Extracting the MySQL binary package"
    if [[ -f /usr/local/src/${MYSQL_PKG_PREFIX}.tar.xz ]]; then
        _logger warn "${MYSQL_PKG_PREFIX}.tar.xz is already exists in /usr/local/src/，will extract and use ..."
    else
        wget -c ${MYSQL_URL} -P /usr/local/src/
    fi
    cd /usr/local/src
    tar -xf ${MYSQL_PKG_PREFIX}.tar.xz -C /usr/local
    mv /usr/local/${MYSQL_PKG_PREFIX} ${MYSQL_HOME}

    # 3. Create dir and update perimission
    _logger info "3. Create necessary directories, update perimissions and PATH environment variable"
    useradd -r mysql || true
    mkdir -p ${MYSQL_HOME}/{data,logs}
    chown -R mysql:mysql ${MYSQL_HOME}

    echo "export MYSQL_HOME=/usr/local/mysql" >> /etc/profile
    echo "export PATH=\$PATH:\${MYSQL_HOME}/bin" >> /etc/profile
    source /etc/profile && echo -e "PATH: $PATH"

    # 4. Update config
    _logger info "4. Update and verify the MYSQL configuration file"
    [[ -f ${MYSQL_CONF} ]] && cp -v ${MYSQL_CONF} ${MYSQL_CONF}.bak
    tee ${MYSQL_CONF} <<-EOF
[mysqld]
## Base settings
server-id = 1
port = ${MYSQL_LISTEN_PORT}
basedir = ${MYSQL_HOME}
datadir = ${MYSQL_HOME}/data
socket = /tmp/mysql.sock
pid-file = ${MYSQL_HOME}/data/mysqld.pid
slow_query_log = 1
slow_query_log_file = /usr/local/mysql/logs/slow.log
long_query_time = 2
lower_case_table_names = 1

## Bin-log settings
log-bin = mysql-bin
relay-log = mysql-relay-bin
max_binlog_size = 100M
binlog_expire_logs_auto_purge = ON
binlog_expire_logs_seconds = 604800
binlog_checksum = None
log_replica_updates = ON
gtid_mode = ON                   # Enable GTID mode
enforce_gtid_consistency = ON    # Enforce GTID consistency check

[client]
user = root
host = localhost
password = "${MYSQL_ROOT_PASSWD}"
socket = /tmp/mysql.sock  # Use the mysql.sock generated by the server above

!includedir /etc/my.cnf.d/
EOF

    _logger info "Validate the configuration file: /etc/my.cnf"
    mysqld --validate-config && echo "It's ok."

    # 5. Init database
    _logger info "5. Initialize MySQL database"
    mysqld --initialize-insecure --user=mysql
    #mysqld --defaults-file=${MYSQL_CONF} --user=mysql &
    #pkill -9 mysql

    # 6. Manager by systemctl
    _logger info "6. Inject the service unit file, manage and start using systemctl"
    tee /etc/systemd/system/mysqld.service <<-EOF
[Unit]
Description=Mysql Server
Documentation=man:mysqld(8)
Documentation=https://dev.mysql.com/doc/refman/en/using-systemd.html
After=network.target
After=syslog.target

[Service]
User=mysql
Group=mysql
ExecStart=/usr/local/mysql/bin/mysqld --defaults-file=/etc/my.cnf
ExecStop=/bin/kill -s QUIT $MAIN
Restart=on-failure
RestartForceExitStatus=16
RestartPreventExitStatus=1

[Install]
WantedBy=multi-user.target
EOF

    systemctl enable --now mysqld && sleep 3
    systemctl status --no-pager -l mysqld && echo

    # 7. Open firewall ports
    _logger info "7. Check and open the corresponding firewall ports"
    if systemctl status firewalld >/dev/null; then
        firewall-cmd --add-port={${MYSQL_LISTEN_PORT},33060}/tcp --permanent >/dev/null 2>&1
        firewall-cmd --reload >/dev/null 2>&1
        echo -e "Current open ports in the firewall: $(firewall-cmd --list-ports)"
    else
        _logger warn "System firewalld is currently disabled."
    fi

    # 8. Install mysql client and execute an SQL
    _logger info "8. Essential client CLI tools and execute an SQL"
    dnf install -qy mysql >/dev/null
    mysql -u root --skip-password <<< "${INIT_SQL}" 2>/dev/null

    # Summary
    _print_sep -
    _logger info "MySQL service has been successfully installed. Summary:"
    mysqladmin version
    echo -e "\n${GREEN}Local login command: ${RED}mysql${NONE}"
    echo -e "${GREEN}Remote login command: ${RED}${REMOTE_LOGIN_CMD}${NONE}"
}

function remove() {
    MYSQL_HOME=$(awk '/basedir/ {print $3}' /etc/my.cnf)
    MYSQL_HOME=${MYSQL_HOME:-/usr/local/mysql}
    MYSQL_LISTEN_PORT=$(awk '/port/ {print $3}' /etc/my.cnf)
    MYSQL_LISTEN_PORT=${MYSQL_LISTEN_PORT:-3306}

    [[ -d ${MYSQL_HOME} ]] || { _logger error "MySQL is not installed." && exit 1; }

    _logger info "check and kill processes ..."
    for i in $(seq 1 10); do
        { ! ps -ef | grep "[m]ysql" >/dev/null && break; } || { pkill -QUIT mysql && sleep 3; }
    done

    _logger info "delete software root dir and other resource ..."
    rm -rfv ${MYSQL_HOME}
    userdel mysql
    firewall-cmd --permanent --remove-port={${MYSQL_LISTEN_PORT},33060}/tcp --permanent >/dev/null 2>&1 || true
    firewall-cmd --reload >/dev/null 2>&1 || true
    sed -i "/MYSQL_HOME/d" /etc/profile && source /etc/profile

    _print_sep -
    _logger info "MySQL has been successfully removed.\n"
}

case $1 in
    install)
        install $2 $3 $4 $5
        ;;
    remove)
        remove $2
        ;;
    *)
        printf "Invalid option $*\n"
        printf "${GREEN}Usage: ${NONE}\n"
        printf "    ${GRAY}bash ${BLUE}$0 ${GREEN}install 8.4.4 ${GRAY}mysql_root_passwd /usr/local/mysql 3306 ${NONE}\n"
        printf "    ${GRAY}bash ${BLUE}$0 ${GREEN}remove${NONE}\n"
        ;;
esac
